import { useRouter } from "next/router";
import Head from "next/head";
import Chatroom from "../../components/chatroom";

import { client } from "../_app";

export default function Space() {
  const router = useRouter();
  const { id } = router.query;

  console.log(id);

  return (
    <>
      <Head>
        <title>SpaceChat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Chatroom client={client} />
      </main>
    </>
  )
}
